In [1]:
import numpy as np

### Criando arrays com números específicos

In [2]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


Você pode também utilizar np.array para criar array de duas dimensões. Para criar um array bidimensional, você deve passar uma lista de listas.

In [3]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


### Criando array com sequências de números
Você pode preencher um array com uma sequência de número:

In [4]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


O np.arange gera uma sequência que inclui o primeiro valor da sequência (5), mas para antes do último valor da sequência

### Preencher arrays com números aleatórios
Numpy possui várias funções para preencher arrays com números aleatórios. Por exemplo, np.random.randint gera inteiros aleatórios entre um valor menor e um valor maior. A chamada seguinte preenche um array com 6 elementos com inteiros entre 50 e 100.

In [5]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=100, size=6)
print(random_integers_between_50_and_100)

[85 67 55 51 84 64]


Para criar valores de ponto flutuante aleatórios entre 0 e 1, chame np.random.random. Por exemplo:

In [6]:
random_floats_between_0_and_1 = np.random.random(6)
print(random_floats_between_0_and_1)

[0.1112354  0.69646959 0.11458402 0.20345288 0.43428959 0.70921226]


### Operações matemáticas no Numpy
Se você quer adicionar ou subtrair dois arrays, na álgebra linear requer que os dois operandos tenham as mesmas dimensões. Além disso, se você quer multiplicar dois arrays, na álgebra linear impõe uma regra restrita sobre as dimensões dos operandos. Felizmente, o Numpy utiliza um truque chamando broadcasting para contornar essas restrições. O broadcasting permite que você realize operações matemáticas em arrays de diferentes dimensões. Por exemplo, a operação seguinte utiliza broadcasting para adicionar 2.0 a cada elemento do código da célula anterior.

In [7]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.1112354  2.69646959 2.11458402 2.20345288 2.43428959 2.70921226]


A operação seguinte também utiliza broadcasting para multiplicar cada elemento do array por 3.

In [8]:
random_integer_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integer_between_150_and_300)

[255 201 165 153 252 192]


### Tarefa 1: Crie um conjunto de dados linear
O seu objetivo é criar um simples conjunto de dados consistindo de uma única característica e um rótulo a seguir:
1. Atribua uma sequência de inteiros de 6 até 20 (inclusive) com Numpy array chamado feature.
2. Atribua 15 valores a um Numpy array chamado label de modo que:
```
label = (3)(feature) + 4
```
Por exemplo, o primeiro valor para `label` deve ser:
```
label = (3)(6) + 4 = 22
```

In [9]:
feature = np.arange(6, 21)
print(feature)
label = 3 * feature + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


### Tarefa 2: Adicione ruído ao conjunto de dados
Faça seu conjunto de dados mais realista, adicione um pouco de ruído aleatório para cada elemento do `label` array que você criou na tarefa 1. Para ser mais preciso, modifique cada valor do `label` adicionando um valor de ponto flutuante aleatório entre -2 e 2. Não confie no broadcasting para fazer isso. Ao invés disso, crie um array de ruído tendo a mesma dimensão que o `label`.

In [13]:
noise = np.random.random(size=label.shape) * 4 - 2
print(noise)
label = label + noise
print(label)

[ 1.4141668   1.31987542 -0.7435896  -1.89939649  0.86694942  1.20703077
  1.71288032 -1.18817104  0.02115058 -1.65984429 -1.46614819 -1.15841295
 -1.55243513 -1.32816692 -1.62403608]
[23.4141668  26.31987542 27.2564104  29.10060351 34.86694942 38.20703077
 41.71288032 41.81182896 46.02115058 47.34015571 50.53385181 53.84158705
 56.44756487 59.67183308 62.37596392]
